/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.12.0.240.2 */
/* Module Version: 5.1 */
/* C:\lscc\diamond\3.12\ispfpga\bin\nt64\scuba.exe -w -n queue_64 -lang verilog -synth lse -bus_exp 7 -bb -arch sa5p00g -type ebfifo -sync_mode -depth 64 -width 8 -no_enable -pe -1 -pf -1 -reset_rel SYNC -fill -fdc C:/Users/Justin/Documents/Lattice Projects/Ultra64_Components/queue_64/queue_64.fdc  */
/* Tue Sep 07 21:19:25 2021 */


`timescale 1 ns / 1 ps
module queue_64 (Data, Clock, WrEn, RdEn, Reset, Q, WCNT, Empty, Full)/* synthesis NGD_DRC_MASK=1 */;
    input wire [7:0] Data;
    input wire Clock;
    input wire WrEn;
    input wire RdEn;
    input wire Reset;
    output wire [7:0] Q;
    output wire [6:0] WCNT;
    output wire Empty;
    output wire Full;

    wire invout_1;
    wire invout_0;
    wire rden_i_inv;
    wire fcnt_en;
    wire empty_i;
    wire empty_d;
    wire full_i;
    wire full_d;
    wire ifcount_0;
    wire ifcount_1;
    wire bdcnt_bctr_ci;
    wire ifcount_2;
    wire ifcount_3;
    wire co0;
    wire ifcount_4;
    wire ifcount_5;
    wire co1;
    wire ifcount_6;
    wire co3;
    wire cnt_con;
    wire co2;
    wire cmp_ci;
    wire rden_i;
    wire co0_1;
    wire co1_1;
    wire co2_1;
    wire cmp_le_1;
    wire cmp_le_1_c;
    wire cmp_ci_1;
    wire fcount_0;
    wire fcount_1;
    wire co0_2;
    wire fcount_2;
    wire fcount_3;
    wire co1_2;
    wire wren_i;
    wire fcount_4;
    wire fcount_5;
    wire co2_2;
    wire wren_i_inv;
    wire fcount_6;
    wire cmp_ge_d1;
    wire cmp_ge_d1_c;
    wire iwcount_0;
    wire iwcount_1;
    wire w_ctr_ci;
    wire wcount_0;
    wire wcount_1;
    wire iwcount_2;
    wire iwcount_3;
    wire co0_3;
    wire wcount_2;
    wire wcount_3;
    wire iwcount_4;
    wire iwcount_5;
    wire co1_3;
    wire wcount_4;
    wire wcount_5;
    wire iwcount_6;
    wire co3_1;
    wire co2_3;
    wire wcount_6;
    wire ircount_0;
    wire ircount_1;
    wire r_ctr_ci;
    wire rcount_0;
    wire rcount_1;
    wire ircount_2;
    wire ircount_3;
    wire co0_4;
    wire rcount_2;
    wire rcount_3;
    wire ircount_4;
    wire ircount_5;
    wire co1_4;
    wire rcount_4;
    wire rcount_5;
    wire ircount_6;
    wire co3_2;
    wire scuba_vhi;
    wire co2_4;
    wire rcount_6;
    wire scuba_vlo;

    AND2 AND2_t3 (.A(WrEn), .B(invout_1), .Z(wren_i));

    INVERTED INV_3 (.A(full_i), .Z(invout_1));

    AND2 AND2_t2 (.A(RdEn), .B(invout_0), .Z(rden_i));

    INVERTED INV_2 (.A(empty_i), .Z(invout_0));

    AND2 AND2_t1 (.A(wren_i), .B(rden_i_inv), .Z(cnt_con));

    XOR2 XOR2_t0 (.A(wren_i), .B(rden_i), .Z(fcnt_en));

    INVERTED INV_1 (.A(rden_i), .Z(rden_i_inv));

    INVERTED INV_0 (.A(wren_i), .Z(wren_i_inv));

    defparam LUT4_1.INIT =  16'h3232 ;
    LUT4 LUT4_1 (.D(scuba_vlo), .C(cmp_le_1), .B(wren_i), .A(empty_i), 
        .Z(empty_d));

    defparam LUT4_0.INIT =  16'h3232 ;
    LUT4 LUT4_0 (.D(scuba_vlo), .C(cmp_ge_d1), .B(rden_i), .A(full_i), 
        .Z(full_d));

    defparam pdp_ram_0_0_0.INIT_DATA = "STATIC" ;
    defparam pdp_ram_0_0_0.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam pdp_ram_0_0_0.CSDECODE_B = "0b000" ;
    defparam pdp_ram_0_0_0.CSDECODE_A = "0b000" ;
    defparam pdp_ram_0_0_0.WRITEMODE_B = "NORMAL" ;
    defparam pdp_ram_0_0_0.WRITEMODE_A = "NORMAL" ;
    defparam pdp_ram_0_0_0.GSR = "ENABLED" ;
    defparam pdp_ram_0_0_0.RESETMODE = "ASYNC" ;
    defparam pdp_ram_0_0_0.REGMODE_B = "NOREG" ;
    defparam pdp_ram_0_0_0.REGMODE_A = "NOREG" ;
    defparam pdp_ram_0_0_0.DATA_WIDTH_B = 9 ;
    defparam pdp_ram_0_0_0.DATA_WIDTH_A = 9 ;
    DP16KD pdp_ram_0_0_0 (.DIA17(scuba_vlo), .DIA16(scuba_vlo), .DIA15(scuba_vlo), 
        .DIA14(scuba_vlo), .DIA13(scuba_vlo), .DIA12(scuba_vlo), .DIA11(scuba_vlo), 
        .DIA10(scuba_vlo), .DIA9(scuba_vlo), .DIA8(scuba_vlo), .DIA7(Data[7]), 
        .DIA6(Data[6]), .DIA5(Data[5]), .DIA4(Data[4]), .DIA3(Data[3]), 
        .DIA2(Data[2]), .DIA1(Data[1]), .DIA0(Data[0]), .ADA13(scuba_vlo), 
        .ADA12(scuba_vlo), .ADA11(scuba_vlo), .ADA10(scuba_vlo), .ADA9(scuba_vlo), 
        .ADA8(wcount_5), .ADA7(wcount_4), .ADA6(wcount_3), .ADA5(wcount_2), 
        .ADA4(wcount_1), .ADA3(wcount_0), .ADA2(scuba_vlo), .ADA1(scuba_vlo), 
        .ADA0(scuba_vlo), .CEA(wren_i), .OCEA(wren_i), .CLKA(Clock), .WEA(scuba_vhi), 
        .CSA2(scuba_vlo), .CSA1(scuba_vlo), .CSA0(scuba_vlo), .RSTA(Reset), 
        .DIB17(scuba_vlo), .DIB16(scuba_vlo), .DIB15(scuba_vlo), .DIB14(scuba_vlo), 
        .DIB13(scuba_vlo), .DIB12(scuba_vlo), .DIB11(scuba_vlo), .DIB10(scuba_vlo), 
        .DIB9(scuba_vlo), .DIB8(scuba_vlo), .DIB7(scuba_vlo), .DIB6(scuba_vlo), 
        .DIB5(scuba_vlo), .DIB4(scuba_vlo), .DIB3(scuba_vlo), .DIB2(scuba_vlo), 
        .DIB1(scuba_vlo), .DIB0(scuba_vlo), .ADB13(scuba_vlo), .ADB12(scuba_vlo), 
        .ADB11(scuba_vlo), .ADB10(scuba_vlo), .ADB9(scuba_vlo), .ADB8(rcount_5), 
        .ADB7(rcount_4), .ADB6(rcount_3), .ADB5(rcount_2), .ADB4(rcount_1), 
        .ADB3(rcount_0), .ADB2(scuba_vlo), .ADB1(scuba_vlo), .ADB0(scuba_vlo), 
        .CEB(rden_i), .OCEB(rden_i), .CLKB(Clock), .WEB(scuba_vlo), .CSB2(scuba_vlo), 
        .CSB1(scuba_vlo), .CSB0(scuba_vlo), .RSTB(Reset), .DOA17(), .DOA16(), 
        .DOA15(), .DOA14(), .DOA13(), .DOA12(), .DOA11(), .DOA10(), .DOA9(), 
        .DOA8(), .DOA7(), .DOA6(), .DOA5(), .DOA4(), .DOA3(), .DOA2(), .DOA1(), 
        .DOA0(), .DOB17(), .DOB16(), .DOB15(), .DOB14(), .DOB13(), .DOB12(), 
        .DOB11(), .DOB10(), .DOB9(), .DOB8(), .DOB7(Q[7]), .DOB6(Q[6]), 
        .DOB5(Q[5]), .DOB4(Q[4]), .DOB3(Q[3]), .DOB2(Q[2]), .DOB1(Q[1]), 
        .DOB0(Q[0]))
             /* synthesis MEM_LPC_FILE="queue_64.lpc" */
             /* synthesis MEM_INIT_FILE="" */;

    FD1P3DX FF_22 (.D(ifcount_0), .SP(fcnt_en), .CK(Clock), .CD(Reset), 
        .Q(fcount_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_21 (.D(ifcount_1), .SP(fcnt_en), .CK(Clock), .CD(Reset), 
        .Q(fcount_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_20 (.D(ifcount_2), .SP(fcnt_en), .CK(Clock), .CD(Reset), 
        .Q(fcount_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_19 (.D(ifcount_3), .SP(fcnt_en), .CK(Clock), .CD(Reset), 
        .Q(fcount_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_18 (.D(ifcount_4), .SP(fcnt_en), .CK(Clock), .CD(Reset), 
        .Q(fcount_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_17 (.D(ifcount_5), .SP(fcnt_en), .CK(Clock), .CD(Reset), 
        .Q(fcount_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_16 (.D(ifcount_6), .SP(fcnt_en), .CK(Clock), .CD(Reset), 
        .Q(fcount_6))
             /* synthesis GSR="ENABLED" */;

    FD1S3BX FF_15 (.D(empty_d), .CK(Clock), .PD(Reset), .Q(empty_i))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_14 (.D(full_d), .CK(Clock), .CD(Reset), .Q(full_i))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_13 (.D(iwcount_0), .SP(wren_i), .CK(Clock), .CD(Reset), .Q(wcount_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_12 (.D(iwcount_1), .SP(wren_i), .CK(Clock), .CD(Reset), .Q(wcount_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_11 (.D(iwcount_2), .SP(wren_i), .CK(Clock), .CD(Reset), .Q(wcount_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_10 (.D(iwcount_3), .SP(wren_i), .CK(Clock), .CD(Reset), .Q(wcount_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_9 (.D(iwcount_4), .SP(wren_i), .CK(Clock), .CD(Reset), .Q(wcount_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_8 (.D(iwcount_5), .SP(wren_i), .CK(Clock), .CD(Reset), .Q(wcount_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_7 (.D(iwcount_6), .SP(wren_i), .CK(Clock), .CD(Reset), .Q(wcount_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_6 (.D(ircount_0), .SP(rden_i), .CK(Clock), .CD(Reset), .Q(rcount_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_5 (.D(ircount_1), .SP(rden_i), .CK(Clock), .CD(Reset), .Q(rcount_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_4 (.D(ircount_2), .SP(rden_i), .CK(Clock), .CD(Reset), .Q(rcount_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_3 (.D(ircount_3), .SP(rden_i), .CK(Clock), .CD(Reset), .Q(rcount_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_2 (.D(ircount_4), .SP(rden_i), .CK(Clock), .CD(Reset), .Q(rcount_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_1 (.D(ircount_5), .SP(rden_i), .CK(Clock), .CD(Reset), .Q(rcount_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_0 (.D(ircount_6), .SP(rden_i), .CK(Clock), .CD(Reset), .Q(rcount_6))
             /* synthesis GSR="ENABLED" */;

    defparam bdcnt_bctr_cia.INJECT1_1 = "NO" ;
    defparam bdcnt_bctr_cia.INJECT1_0 = "NO" ;
    defparam bdcnt_bctr_cia.INIT1 =  16'h66AA ;
    defparam bdcnt_bctr_cia.INIT0 =  16'h66AA ;
    CCU2C bdcnt_bctr_cia (.A0(scuba_vlo), .A1(cnt_con), .B0(scuba_vlo), 
        .B1(cnt_con), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(), .S0(), .S1(), .COUT(bdcnt_bctr_ci));

    defparam bdcnt_bctr_0.INJECT1_1 = "NO" ;
    defparam bdcnt_bctr_0.INJECT1_0 = "NO" ;
    defparam bdcnt_bctr_0.INIT1 =  16'h99AA ;
    defparam bdcnt_bctr_0.INIT0 =  16'h99AA ;
    CCU2C bdcnt_bctr_0 (.A0(fcount_0), .A1(fcount_1), .B0(cnt_con), .B1(cnt_con), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(bdcnt_bctr_ci), .S0(ifcount_0), .S1(ifcount_1), .COUT(co0));

    defparam bdcnt_bctr_1.INJECT1_1 = "NO" ;
    defparam bdcnt_bctr_1.INJECT1_0 = "NO" ;
    defparam bdcnt_bctr_1.INIT1 =  16'h99AA ;
    defparam bdcnt_bctr_1.INIT0 =  16'h99AA ;
    CCU2C bdcnt_bctr_1 (.A0(fcount_2), .A1(fcount_3), .B0(cnt_con), .B1(cnt_con), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co0), .S0(ifcount_2), .S1(ifcount_3), .COUT(co1));

    defparam bdcnt_bctr_2.INJECT1_1 = "NO" ;
    defparam bdcnt_bctr_2.INJECT1_0 = "NO" ;
    defparam bdcnt_bctr_2.INIT1 =  16'h99AA ;
    defparam bdcnt_bctr_2.INIT0 =  16'h99AA ;
    CCU2C bdcnt_bctr_2 (.A0(fcount_4), .A1(fcount_5), .B0(cnt_con), .B1(cnt_con), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co1), .S0(ifcount_4), .S1(ifcount_5), .COUT(co2));

    defparam bdcnt_bctr_3.INJECT1_1 = "NO" ;
    defparam bdcnt_bctr_3.INJECT1_0 = "NO" ;
    defparam bdcnt_bctr_3.INIT1 =  16'h99AA ;
    defparam bdcnt_bctr_3.INIT0 =  16'h99AA ;
    CCU2C bdcnt_bctr_3 (.A0(fcount_6), .A1(scuba_vlo), .B0(cnt_con), .B1(cnt_con), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co2), .S0(ifcount_6), .S1(), .COUT(co3));

    defparam e_cmp_ci_a.INJECT1_1 = "NO" ;
    defparam e_cmp_ci_a.INJECT1_0 = "NO" ;
    defparam e_cmp_ci_a.INIT1 =  16'h66AA ;
    defparam e_cmp_ci_a.INIT0 =  16'h66AA ;
    CCU2C e_cmp_ci_a (.A0(scuba_vhi), .A1(scuba_vhi), .B0(scuba_vhi), .B1(scuba_vhi), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(), .S0(), .S1(), .COUT(cmp_ci));

    defparam e_cmp_0.INJECT1_1 = "NO" ;
    defparam e_cmp_0.INJECT1_0 = "NO" ;
    defparam e_cmp_0.INIT1 =  16'h99AA ;
    defparam e_cmp_0.INIT0 =  16'h99AA ;
    CCU2C e_cmp_0 (.A0(rden_i), .A1(scuba_vlo), .B0(fcount_0), .B1(fcount_1), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(cmp_ci), .S0(), .S1(), .COUT(co0_1));

    defparam e_cmp_1.INJECT1_1 = "NO" ;
    defparam e_cmp_1.INJECT1_0 = "NO" ;
    defparam e_cmp_1.INIT1 =  16'h99AA ;
    defparam e_cmp_1.INIT0 =  16'h99AA ;
    CCU2C e_cmp_1 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(fcount_2), .B1(fcount_3), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co0_1), .S0(), .S1(), .COUT(co1_1));

    defparam e_cmp_2.INJECT1_1 = "NO" ;
    defparam e_cmp_2.INJECT1_0 = "NO" ;
    defparam e_cmp_2.INIT1 =  16'h99AA ;
    defparam e_cmp_2.INIT0 =  16'h99AA ;
    CCU2C e_cmp_2 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(fcount_4), .B1(fcount_5), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co1_1), .S0(), .S1(), .COUT(co2_1));

    defparam e_cmp_3.INJECT1_1 = "NO" ;
    defparam e_cmp_3.INJECT1_0 = "NO" ;
    defparam e_cmp_3.INIT1 =  16'h99AA ;
    defparam e_cmp_3.INIT0 =  16'h99AA ;
    CCU2C e_cmp_3 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(fcount_6), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co2_1), .S0(), .S1(), .COUT(cmp_le_1_c));

    defparam a0.INJECT1_1 = "NO" ;
    defparam a0.INJECT1_0 = "NO" ;
    defparam a0.INIT1 =  16'h66AA ;
    defparam a0.INIT0 =  16'h66AA ;
    CCU2C a0 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(cmp_le_1_c), .S0(cmp_le_1), .S1(), .COUT());

    defparam g_cmp_ci_a.INJECT1_1 = "NO" ;
    defparam g_cmp_ci_a.INJECT1_0 = "NO" ;
    defparam g_cmp_ci_a.INIT1 =  16'h66AA ;
    defparam g_cmp_ci_a.INIT0 =  16'h66AA ;
    CCU2C g_cmp_ci_a (.A0(scuba_vhi), .A1(scuba_vhi), .B0(scuba_vhi), .B1(scuba_vhi), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(), .S0(), .S1(), .COUT(cmp_ci_1));

    defparam g_cmp_0.INJECT1_1 = "NO" ;
    defparam g_cmp_0.INJECT1_0 = "NO" ;
    defparam g_cmp_0.INIT1 =  16'h99AA ;
    defparam g_cmp_0.INIT0 =  16'h99AA ;
    CCU2C g_cmp_0 (.A0(fcount_0), .A1(fcount_1), .B0(wren_i), .B1(wren_i), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(cmp_ci_1), .S0(), .S1(), .COUT(co0_2));

    defparam g_cmp_1.INJECT1_1 = "NO" ;
    defparam g_cmp_1.INJECT1_0 = "NO" ;
    defparam g_cmp_1.INIT1 =  16'h99AA ;
    defparam g_cmp_1.INIT0 =  16'h99AA ;
    CCU2C g_cmp_1 (.A0(fcount_2), .A1(fcount_3), .B0(wren_i), .B1(wren_i), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co0_2), .S0(), .S1(), .COUT(co1_2));

    defparam g_cmp_2.INJECT1_1 = "NO" ;
    defparam g_cmp_2.INJECT1_0 = "NO" ;
    defparam g_cmp_2.INIT1 =  16'h99AA ;
    defparam g_cmp_2.INIT0 =  16'h99AA ;
    CCU2C g_cmp_2 (.A0(fcount_4), .A1(fcount_5), .B0(wren_i), .B1(wren_i), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co1_2), .S0(), .S1(), .COUT(co2_2));

    defparam g_cmp_3.INJECT1_1 = "NO" ;
    defparam g_cmp_3.INJECT1_0 = "NO" ;
    defparam g_cmp_3.INIT1 =  16'h99AA ;
    defparam g_cmp_3.INIT0 =  16'h99AA ;
    CCU2C g_cmp_3 (.A0(fcount_6), .A1(scuba_vlo), .B0(wren_i_inv), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co2_2), .S0(), .S1(), .COUT(cmp_ge_d1_c));

    defparam a1.INJECT1_1 = "NO" ;
    defparam a1.INJECT1_0 = "NO" ;
    defparam a1.INIT1 =  16'h66AA ;
    defparam a1.INIT0 =  16'h66AA ;
    CCU2C a1 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(cmp_ge_d1_c), .S0(cmp_ge_d1), .S1(), .COUT());

    defparam w_ctr_cia.INJECT1_1 = "NO" ;
    defparam w_ctr_cia.INJECT1_0 = "NO" ;
    defparam w_ctr_cia.INIT1 =  16'h66AA ;
    defparam w_ctr_cia.INIT0 =  16'h66AA ;
    CCU2C w_ctr_cia (.A0(scuba_vlo), .A1(scuba_vhi), .B0(scuba_vlo), .B1(scuba_vhi), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(), .S0(), .S1(), .COUT(w_ctr_ci));

    defparam w_ctr_0.INJECT1_1 = "NO" ;
    defparam w_ctr_0.INJECT1_0 = "NO" ;
    defparam w_ctr_0.INIT1 =  16'h66AA ;
    defparam w_ctr_0.INIT0 =  16'h66AA ;
    CCU2C w_ctr_0 (.A0(wcount_0), .A1(wcount_1), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(w_ctr_ci), .S0(iwcount_0), .S1(iwcount_1), .COUT(co0_3));

    defparam w_ctr_1.INJECT1_1 = "NO" ;
    defparam w_ctr_1.INJECT1_0 = "NO" ;
    defparam w_ctr_1.INIT1 =  16'h66AA ;
    defparam w_ctr_1.INIT0 =  16'h66AA ;
    CCU2C w_ctr_1 (.A0(wcount_2), .A1(wcount_3), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co0_3), .S0(iwcount_2), .S1(iwcount_3), .COUT(co1_3));

    defparam w_ctr_2.INJECT1_1 = "NO" ;
    defparam w_ctr_2.INJECT1_0 = "NO" ;
    defparam w_ctr_2.INIT1 =  16'h66AA ;
    defparam w_ctr_2.INIT0 =  16'h66AA ;
    CCU2C w_ctr_2 (.A0(wcount_4), .A1(wcount_5), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co1_3), .S0(iwcount_4), .S1(iwcount_5), .COUT(co2_3));

    defparam w_ctr_3.INJECT1_1 = "NO" ;
    defparam w_ctr_3.INJECT1_0 = "NO" ;
    defparam w_ctr_3.INIT1 =  16'h66AA ;
    defparam w_ctr_3.INIT0 =  16'h66AA ;
    CCU2C w_ctr_3 (.A0(wcount_6), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co2_3), .S0(iwcount_6), .S1(), .COUT(co3_1));

    defparam r_ctr_cia.INJECT1_1 = "NO" ;
    defparam r_ctr_cia.INJECT1_0 = "NO" ;
    defparam r_ctr_cia.INIT1 =  16'h66AA ;
    defparam r_ctr_cia.INIT0 =  16'h66AA ;
    CCU2C r_ctr_cia (.A0(scuba_vlo), .A1(scuba_vhi), .B0(scuba_vlo), .B1(scuba_vhi), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(), .S0(), .S1(), .COUT(r_ctr_ci));

    defparam r_ctr_0.INJECT1_1 = "NO" ;
    defparam r_ctr_0.INJECT1_0 = "NO" ;
    defparam r_ctr_0.INIT1 =  16'h66AA ;
    defparam r_ctr_0.INIT0 =  16'h66AA ;
    CCU2C r_ctr_0 (.A0(rcount_0), .A1(rcount_1), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(r_ctr_ci), .S0(ircount_0), .S1(ircount_1), .COUT(co0_4));

    defparam r_ctr_1.INJECT1_1 = "NO" ;
    defparam r_ctr_1.INJECT1_0 = "NO" ;
    defparam r_ctr_1.INIT1 =  16'h66AA ;
    defparam r_ctr_1.INIT0 =  16'h66AA ;
    CCU2C r_ctr_1 (.A0(rcount_2), .A1(rcount_3), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co0_4), .S0(ircount_2), .S1(ircount_3), .COUT(co1_4));

    defparam r_ctr_2.INJECT1_1 = "NO" ;
    defparam r_ctr_2.INJECT1_0 = "NO" ;
    defparam r_ctr_2.INIT1 =  16'h66AA ;
    defparam r_ctr_2.INIT0 =  16'h66AA ;
    CCU2C r_ctr_2 (.A0(rcount_4), .A1(rcount_5), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co1_4), .S0(ircount_4), .S1(ircount_5), .COUT(co2_4));

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    defparam r_ctr_3.INJECT1_1 = "NO" ;
    defparam r_ctr_3.INJECT1_0 = "NO" ;
    defparam r_ctr_3.INIT1 =  16'h66AA ;
    defparam r_ctr_3.INIT0 =  16'h66AA ;
    CCU2C r_ctr_3 (.A0(rcount_6), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co2_4), .S0(ircount_6), .S1(), .COUT(co3_2));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    assign WCNT[0] = fcount_0;
    assign WCNT[1] = fcount_1;
    assign WCNT[2] = fcount_2;
    assign WCNT[3] = fcount_3;
    assign WCNT[4] = fcount_4;
    assign WCNT[5] = fcount_5;
    assign WCNT[6] = fcount_6;
    assign Empty = empty_i;
    assign Full = full_i;


    // exemplar begin
    // exemplar attribute pdp_ram_0_0_0 MEM_LPC_FILE queue_64.lpc
    // exemplar attribute pdp_ram_0_0_0 MEM_INIT_FILE 
    // exemplar attribute FF_22 GSR ENABLED
    // exemplar attribute FF_21 GSR ENABLED
    // exemplar attribute FF_20 GSR ENABLED
    // exemplar attribute FF_19 GSR ENABLED
    // exemplar attribute FF_18 GSR ENABLED
    // exemplar attribute FF_17 GSR ENABLED
    // exemplar attribute FF_16 GSR ENABLED
    // exemplar attribute FF_15 GSR ENABLED
    // exemplar attribute FF_14 GSR ENABLED
    // exemplar attribute FF_13 GSR ENABLED
    // exemplar attribute FF_12 GSR ENABLED
    // exemplar attribute FF_11 GSR ENABLED
    // exemplar attribute FF_10 GSR ENABLED
    // exemplar attribute FF_9 GSR ENABLED
    // exemplar attribute FF_8 GSR ENABLED
    // exemplar attribute FF_7 GSR ENABLED
    // exemplar attribute FF_6 GSR ENABLED
    // exemplar attribute FF_5 GSR ENABLED
    // exemplar attribute FF_4 GSR ENABLED
    // exemplar attribute FF_3 GSR ENABLED
    // exemplar attribute FF_2 GSR ENABLED
    // exemplar attribute FF_1 GSR ENABLED
    // exemplar attribute FF_0 GSR ENABLED
    // exemplar end

endmodule
